package com.myspace.initial_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.Integer age;
	private int celNumber;
	private java.util.List<java.lang.String> descriptions;

	public Customer() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.util.List<java.lang.String> getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(java.util.List<java.lang.String> descriptions) {
		this.descriptions = descriptions;
	}

	public int getCelNumber() {
		return this.celNumber;
	}

	public void setCelNumber(int celNumber) {
		this.celNumber = celNumber;
	}

	public Customer(java.lang.String name, java.lang.Integer age,
			int celNumber, java.util.List<java.lang.String> descriptions) {
		this.name = name;
		this.age = age;
		this.celNumber = celNumber;
		this.descriptions = descriptions;
	}

}